How many accidents were there in Madrid in 2013?

PREFIX mv: <http://example.org/myVocabulary#>
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT (SUM(?accidents) AS ?TotalAccidentes)
WHERE {
    ?obs a qb:Observation;
        mv:numberOfAccidents ?accidents
}

Give me the number of accidents in Usera for each type of accident

PREFIX mv: <http://example.org/myVocabulary#>
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT ?type (xsd:integer(?num) AS ?nAccidents) 
WHERE {
    ?obs a qb:Observation;
		mv:relatedDistrict "USERA";
		mv:hasAccidentType ?type;
		mv:numberOfAccidents ?num.
}

Give me the number of multiple collisions for each district

PREFIX mv: <http://example.org/myVocabulary#>
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT ?dist (xsd:integer(?num) AS ?nAccidents) 
WHERE {
    ?obs a qb:Observation;
		mv:relatedDistrict ?dist;
		mv:hasAccidentType "MultipleCollision";
		mv:numberOfAccidents ?num.
}

Which is the district were the number of bicycle falls was higher in 2013?

PREFIX mv: <http://example.org/myVocabulary#>
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT ?dist MAX(?num)
WHERE {
    ?obs a qb:Observation;
		mv:relatedDistrict ?dist;
		mv:hasAccidentType BicycleFall;
		mv:numberOfAccidents ?num.
}

Give me the districts with more than 500 accidents in 2013

PREFIX mv: <http://example.org/myVocabulary#>
PREFIX qb: <http://purl.org/linked-data/cube#>


SELECT ?dist ?accidents
WHERE
{
    {
    SELECT ?dist (SUM(?num) AS ?accidents
    WHERE {
        ?obs a qb:Observation;
            mv:relatedDistrict ?dist;
            mv:hasAccidentType ?type;
            mv:numberOfAccidents ?num.
        }
    }
    FILTER (?accidents > 500)
}