#   Assigment 6
#  
#   Javier de la Rúa Martínez 
#   u120009

#
#   Prefixes
#

PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX mv: <http://example.org/myVocabulary#>

#
#   How many accidents were there in Madrid in 2013?
#

SELECT (SUM(?x) AS ?numberOfAccidents) WHERE {
    ?obs a qb:Observation ;
    mv:numberOfAccidents ?x .
}

#
#   Give me the number of accidents in Usera for each type of accident.
#

SELECT ?accidentType xsd:integer(?numberAccidents) AS ?number WHERE {
    ?obs a qb:Observation ;
    mv:relatedDistrict "USERA";
	mv:hasAccidentType ?accidentType ;
	mv:numberOfAccidents ?numberAccidents
}

#
#   Give me the number of multiple collisions for each district
#

SELECT ?x AS ?district xsd:integer(?y) AS ?collisionsNumber WHERE{
    ?obs a qb:Observation ;
    mv:relatedDistrict ?x ;
    mv:hasAccidentType mv:MultipleCollision ;
    mv:numberOfAccidents ?y .
}

#
#   Which is the district were the number of bicycle falls was higher in 2013?
#

SELECT ?x AS ?district xsd:integer(MAX(?y)) AS ?numberAccidents WHERE {
    ?obs a qb:Observation ;
    mv:relatedDistrict ?x ;
    mv:hasAccidentType mv:BicycleFall ;
    mv:numberOfAccidents ?y .
}
ORDER BY DESC(?y) LIMIT 1

#
#   Give me the districts with more than 500 accidents in 2013
#

SELECT ?x AS ?district ?y AS ?accidentNumber WHERE {{
    SELECT ?x SUM(xsd:integer(?z)) AS ?y
    WHERE {
        ?obs a qb:Observation ;
        mv:relatedDistrict ?x ;
        mv:numberOfAccidents ?z . 
    }
}}
HAVING(?y > 500)