# A1. Dame todas las propiedades aplicables a las instancias de la clase
# Politician (<http://dbpedia.org/ontology/Politician>)

SELECT DISTINCT ?properties
WHERE {
  ?x rdf:type <http://dbpedia.org/ontology/Politician>.
  ?x ?properties ?y
}

# A2. Dame todas las propiedades, exceptuando rdf:type, aplicables a las
# instancias de la clase Politician (<http://dbpedia.org/ontology/Politician>)

SELECT DISTINCT ?properties
WHERE {
  ?x rdf:type <http://dbpedia.org/ontology/Politician>.
  ?x ?properties ?y
  MINUS{ ?x rdf:type ?y }
}

# A3. ¿Cuántos valores distintos se pueden encontrar para las propiedades, exceptuando
# rdf:type, de las instancias de la clase Politician (<http://dbpedia.org/ontology/Politician>)?

SELECT COUNT(DISTINCT ?properties)
WHERE {
  ?x rdf:type <http://dbpedia.org/ontology/Politician>.
  ?x ?properties ?y
  MINUS{ ?x rdf:type ?y }
}

# A4. Para cada una de las propiedades, exceptuando rdf:type, aplicables a
# las instancias de la clase Politician (<http://dbpedia.org/ontology/Politician>),
# dime cuántos valores distintos toman en dichas instancias

SELECT COUNT(DISTINCT ?properties)
WHERE {
  ?x rdf:type <http://dbpedia.org/ontology/Politician>.
  ?x ?properties ?y
  MINUS{ ?x rdf:type ?y }
}
GROUP BY ?x

# A5. Para cada una de las propiedades, exceptuando rdf:type, aplicables a
# las instancias de la clase Politician (<http://dbpedia.org/ontology/Politician>),
# dime la media de valores distintos que toman en dichas instancias.

# A6. Para cada una de las propiedades, exceptuando rdf:type, aplicables a
# las instancias de la clase Politician (<http://dbpedia.org/ontology/Politician>),
# dime el máximo número de valores distintos que toman entre todas sus instancias,
# ordenado de mayor a menor
