Alberto Mendiolagoitia Sánchez - V130096

   A1. Dame todas las propiedades aplicables a las instancias de la clase Politician (http://dbpedia.org/ontology/Politician)
PREFIX pr:<http://dbpedia.org/ontology/>
SELECT ?prop WHERE {
					?x a pr:Politician.
					?x ?prop ?y. 
				}

   A2. Dame todas las propiedades, exceptuando rdf:type, aplicables a las instancias de la clase Politician (http://dbpedia.org/ontology/Politician)
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX pr:<http://dbpedia.org/ontology/>
SELECT ?prop WHERE 	{
						?x a pr:Politician.
						?x ?prop ?y. 
						FILTER ( ?prop != rdfs:type) 
					}

   A3. ¿Cuántos valores distintos se pueden encontrar para las propiedades, exceptuando rdf:type, de las instancias de la clase Politician 
(http://dbpedia.org/ontology/Politician)?
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX pr:<http://dbpedia.org/ontology/>
SELECT COUNT(DISTINCT ?prop) as ?Count WHERE{
												?x a pr:Politician.
												?x ?prop ?y FILTER ( ?prop != rdfs:type ) 
											}

   A4. Para cada una de las propiedades, exceptuando rdf:type, aplicables a las instancias de la clase Politician (http://dbpedia.org/ontology/Politician), dime cuántos valores distintos toman en dichas instancias
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX pr:<http://dbpedia.org/ontology/>
SELECT DISTINCT ?prop COUNT(?y) WHERE 	{
											?x a pr:Politician.
											?x ?prop ?y FILTER ( ?prop != rdfs:type ) 
										}

   A5. Para cada una de las propiedades, exceptuando rdf:type, aplicables a las instancias de la clase Politician (http://dbpedia.org/ontology/Politician), dime la media de valores distintos que toman en dichas instancias.
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pr:<http://dbpedia.org/ontology/>
SELECT DISTINCT ?prop AVG(?count) WHERE	{ 
											SELECT ?prop COUNT(?y) as ?count WHERE { 
																						?x a pr:Politician. 
																						?x ?prop ?y FILTER ( ?prop != rdfs:type ) 
																					} 
										}

   A6. Para cada una de las propiedades, exceptuando rdf:type, aplicables a las instancias de la clase Politician (http://dbpedia.org/ontology/Politician), dime el máximo número de valores distintos que toman entre todas sus instancias, ordenado de mayor a menor
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX pr:<http://dbpedia.org/ontology/>
SELECT ?prop MAX(?count) as ?m WHERE	{ 
											SELECT ?prop COUNT(DISTINCT ?y) as ?count WHERE	{
																								?x a pr:Politician. 
																								?x ?prop ?y FILTER ( ?prop != rdfs:type ) 
																							} 
										} ORDER BY DESC(?m)